### ISSUE TITLE
webhook: Injection is attempted on pods in kube-system with default configuration from chart

### ISSUE THREAD

**Issue by jeffhubLR** [banzaicloud/bank-vaults#1464]
**Describe the bug**:
The default vault-secrets-webhook chart configuration includes a namespaceSelector that attempts to exclude the `kube-system` namespace (https://github.com/banzaicloud/bank-vaults/blob/master/charts/vault-secrets-webhook/values.yaml#L161). However namespaceSelector operates on labels, as explained best in this issue: https://github.com/kubernetes/kubernetes/issues/75766

If podFailurePolicy is changed to "Fail" from the default of "Ignore" (https://github.com/banzaicloud/bank-vaults/blob/master/charts/vault-secrets-webhook/values.yaml#L150) this can cause pods in kube-system to fail to start, particularly if vault is running in Istio and a single master node cluster has its master node restarted.

This also applies to the namespace where the chart is installed, which is similarly attempted to be excluded here:
https://github.com/banzaicloud/bank-vaults/blob/master/charts/vault-secrets-webhook/templates/apiservice-webhook.yaml#L94

**Expected behaviour**:
kube-system pods are excluded from the mutating admission webhook when using the default chart configuration, or documentation is updated to capture behavior as implemented.

**Steps to reproduce the bug**:
In a cluster with a single master node.
Deploy vault-operator helm chart using default values in helm chart
Deploy vault-secret-webhooks helm chart, setting podsFailurePolicy to False
`helm install vault-secrets-webhook banzaicloud-stable/vault-secrets-webhook --set podsFailurePolicy="Fail"`
Restart the master node.
CNI pod will fail to deploy due to vault-secrets-webhook call failing.

**Additional context**:
None

**Environment details**:
- Kubernetes version (e.g. v1.10.2): 1.20.11
- Cloud-provider/provisioner (e.g. AKS, GKE, EKS, PKE etc): kops
- bank-vaults version (e.g. 0.4.17): chart 1.4.3, vault-secrets-webhook chart 1.5.2
- Install method (e.g. helm or static manifests): helm

/kind bug

**Comment by saitama-dh** [comment]
This issue cost me years of life expectancy.

**Comment by bonifaido** [comment]
These labels are used to be there in previous Kubernetes versions, since the previous setting used to work. I will push a fix for this soon.

**Comment by bonifaido** [comment]
What kind of labels do you have on your `kube-system` currently @jeffhubLR @saitama-dh ?

**Comment by bonifaido** [comment]
According to the official Kubernetes docs this should solve the kube-system mutating issue: https://github.com/banzaicloud/bank-vaults/pull/1479

**Comment by saitama-dh** [comment]
Great news @bonifaido! Thank you.

**Comment by jeffhubLR** [comment]
Thanks @bonifaido . Sorry for the delayed response to your question.
We are on Kubernetes 1.20.11, and the labels on kube-system namespace are:
`applications.argoproj.io/app-name=kube-system,vault-injection=disabled`

Even creating a new namespace does not result in it being labeled by the API server as documented in your link:
```
❯ kubectl create ns test
❯ kubectl get ns test --show-labels
NAME   STATUS   AGE   LABELS
test   Active   63s   <none>
```

All that said, thank you for the fix 👍 I'll work out why our namespaces aren't being labeled appropriately.

**Comment by bonifaido** [comment]
Thank you, and no problem!

I see that you are using kops, it mens that you have really good control what feature flags are you enable, I think you should check this one: https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/#automatic-labelling

**Comment by SantiEich** [comment]
Hi @bonifaido!

I have the latest version

`vault-secrets-webhook             	vault-infra   	1       	2021-12-28 10:32:24.33993 -0300 -03    	deployed	vault-secrets-webhook-1.15.4       	1.14.4`

But the problem persists

`4m10s       Warning   FailedToUpdateEndpoint         endpoints/kube-dns                                  Failed to update endpoint kube-system/kube-dns: Operation cannot be fulfilled on endpoints "kube-dns": the object has been modified; please apply your changes to the latest version and try again
3m57s       Warning   FailedToUpdateEndpointSlices   service/kube-dns                                    Error updating Endpoint Slices for Service kube-system/kube-dns: node "ip-10-16-166-83.us-east-2.compute.internal" not found
2m24s       Warning   FailedCreate                   replicaset/coredns-5c778788f4                       Error creating: Internal error occurred: failed calling webhook "pods.vault-secrets-webhook.admission.banzaicloud.com": Post "https://vault-secrets-webhook.vault-infra.svc:443/pods?timeout=10s": no endpoints available for service "vault-secrets-webhook"
82s         Warning   FailedCreate                   replicaset/metric-server-metrics-server-5d47f947b   Error creating: Internal error occurred: failed calling webhook "pods.vault-secrets-webhook.admission.banzaicloud.com": Post "https://vault-secrets-webhook.vault-infra.svc:443/pods?timeout=10s": no endpoints available for service "vault-secrets-webhook"
24s         Warning   FailedCreate                   daemonset/kube-proxy                                Error creating: Internal error occurred: failed calling webhook "pods.vault-secrets-webhook.admission.banzaicloud.com": Post "https://vault-secrets-webhook.vault-infra.svc:443/pods?timeout=10s": no endpoints available for service "vault-secrets-webhook"
19s         Warning   FailedCreate                   daemonset/aws-node                                  Error creating: Internal error occurred: failed calling webhook "pods.vault-secrets-webhook.admission.banzaicloud.com": Post "https://vault-secrets-webhook.vault-infra.svc:443/pods?timeout=10s": no endpoints available for service "vault-secrets-webhook"`

We use EKS 1.20

Any suggestions to mitigate this problem? This is extremely important to us
