### ISSUE TITLE
Vault Operator chart upgrade 0.6.4 to 0.6.5 is failing 

### ISSUE THREAD

**Issue by akin-ozer** [banzaicloud/bank-vaults#907]
**Describe the bug**:
Vault Operator chart upgrade 0.6.4 to 0.6.5 is failing with following log:

rendered manifests contain a resource that already exists. Unable to continue with install: existing resource conflict: namespace: , name: vaults.vault.banzaicloud.com, existing_kind: apiextensions.k8s.io/v1beta1, Kind=CustomResourceDefinition, new_kind: apiextensions.k8s.io/v1beta1, Kind=CustomResourceDefinition

**Expected behaviour**:
Helm upgrade should work seamlessly between minor releases.

**Steps to reproduce the bug**:
Have installed chart version 0.6.4 and use following helm command to upgrade:

<pre>
helm upgrade --namespace vault \
  --install vault-operator --version 0.6.5 \
  banzaicloud-stable/vault-operator \
  --wait
</pre>

**Environment details**:
- Kubernetes version (e.g. v1.10.2): 1.17.3
- Cloud-provider/provisioner (e.g. AKS, GKE, EKS, PKE etc): Kubeadm
- bank-vaults version (e.g. 0.4.17): helm chart: 0.6.5, bank-vaults: 0.9.0
- Install method (e.g. helm or static manifests): helm
- Logs from the misbehaving component (and any other relevant logs): provided
- Resource definition (possibly in YAML format) that caused the issue, without sensitive data:

<pre>

apiVersion: "vault.banzaicloud.com/v1alpha1"
kind: "Vault"
metadata:
  name: "vault"
  namespace: vault
spec:
  size: 1
  image: vault:1.3.1
  bankVaultsImage: banzaicloud/bank-vaults:0.8.1

  resources:
    vault:
      requests:
        memory: "256Mi"
        cpu: "200m"
      limits:
        memory: "256Mi"
        cpu: "500m"

  annotations:
    common/annotation: "true"

  vaultAnnotations:
    type/instance: "vault"

  vaultConfigurerAnnotations:
    type/instance: "vaultconfigurer"

  vaultLabels:
    example.com/log-format: "json"

  vaultConfigurerLabels:
    example.com/log-format: "string"

running
  serviceAccount: vault

  serviceType: ClusterIP

  ingress:
    annotations:v1beta1-extensions
    spec: {}
  caNamespaces:
    - "vault"

  unsealConfig:
    options:
      preFlightChecks: true
    aws:
      kmsKeyId: redacted

  config:
    storage:
      s3: redacted
    listener:
      tcp:
        address: "0.0.0.0:8200"
        tls_cert_file: /vault/tls/server.crt
        tls_key_file: /vault/tls/server.key
    telemetry:
      statsd_address: localhost:9125
    ui: true
  externalConfig:
    policies:
      - name: allow_all
        rules: path "*" {
          capabilities = ["create", "read", "update", "delete", "list"]
          }
      - name: allow_aws
        rules: path "aws/*" {
          capabilities = ["create", "read", "update", "delete", "list"]
          }
      - name: allow_secrets
        rules: path "secret/*" {
          capabilities = ["create", "read", "update", "delete", "list"]
          }

    auth:
      - type: kubernetes
        roles:
          # Allow every pod in the default namespace to use the secret kv store
          - name: default
            bound_service_account_names: ["default", "vault-secrets-webhook", "vault"]
            bound_service_account_namespaces: ["default", "vswh"]
            policies: ["allow_secrets", "allow_pki"]
            ttl: 1h

      - type: github
        options:
          listing_visibility: "unauth"
        config:
          organization: redacted
        map:
          teams: redacted
          users: redacted
    secrets:
      - path: secret
        type: kv
        description: General secrets.
        options:
          version: 2

  istioEnabled: false
  credentialsConfig:
    env: AWS_SHARED_CREDENTIALS_FILE
    path: /etc/aws/credentials
    secretName: aws-cred

</pre>

/kind bug

**Comment by akin-ozer** [comment]
There is workaround that I found. Just delete that crd with(you would want to remove previous chart before):

> kubectl delete customresourcedefinitions.apiextensions.k8s.io vaults.vault.banzaicloud.com

**Comment by bonifaido** [comment]
We haven't changed the operator chart between the two releases from this point of view. This sounds like an isntall-remove procedure/helm issue.

**Comment by akin-ozer** [comment]
It also happens when you delete the chart and reinstall it. Helm version 3.1.

**Comment by bonifaido** [comment]
I tried to reproduce the above error, but I can't.

```bash
$ helm version
version.BuildInfo{Version:"v3.1.1", GitCommit:"afe70585407b420d0097d07b21c47dc511525ac8", GitTreeState:"clean", GoVersion:"go1.13.8"}
```

```bash
$ helm upgrade --install vault-operator banzaicloud-stable/vault-operator
Release "vault-operator" does not exist. Installing it now.
NAME: vault-operator
LAST DEPLOYED: Tue Mar 10 08:41:51 2020
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
```

```bash
$ kubectl get customresourcedefinitions vaults.vault.banzaicloud.com 
NAME                           CREATED AT
vaults.vault.banzaicloud.com   2020-03-10T07:41:52Z
```

```bash
$ helm delete vault-operator
release "vault-operator" uninstalled
```

```bash
$ kubectl get customresourcedefinitions vaults.vault.banzaicloud.com
Error from server (NotFound): customresourcedefinitions.apiextensions.k8s.io "vaults.vault.banzaicloud.com" not found
```

**Comment by bonifaido** [comment]
Please try the newest chart version 0.6.7 which supports Helm3 a bit better.

**Comment by akin-ozer** [comment]
I get strange error with chart version 0.6.7:

> kubectl get customresourcedefinitions vaults.vault.banzaicloud.com
--none

<pre>
helm upgrade --namespace vault \
  --install vault-operator --version 0.6.7 \
  banzaicloud-stable/vault-operator \
  --wait
</pre>

Gets error:

<pre>
rendered manifests contain a resource that already exists. Unable to continue with install: existing resource conflict: namespace: , name: vaults.vault.banzaicloud.com, existing_kind: apiextensions.k8s.io/v1beta1, Kind=CustomResourceDefinition, new_kind: apiextensions.k8s.io/v1beta1, Kind=CustomResourceDefinition
</pre

> kubectl get customresourcedefinitions vaults.vault.banzaicloud.com

vaults.vault.banzaicloud.com            2020-03-11T08:30:41Z

"helm list -n vault" returns empty in both cases(no failed installation).

**Comment by bonifaido** [comment]
Are you using Helm 3?

**Comment by akin-ozer** [comment]
Yes still 3.1

**Comment by bonifaido** [comment]
You have probably installed the operator to another namespace previously, in this case, the CRD check fails in Helm 3.

I reproduced the "bug" (which is not a bug in this project, as we can't fix it here, but should be fixed in upstream, in Helm 3):

```bash
$ helm upgrade --install vault-operator banzaicloud-stable/vault-operator
Release "vault-operator" has been upgraded. Happy Helming!
NAME: vault-operator
LAST DEPLOYED: Wed Mar 11 09:46:07 2020
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None

$ helm upgrade --install vault-operator banzaicloud-stable/vault-operator
Release "vault-operator" has been upgraded. Happy Helming!
NAME: vault-operator
LAST DEPLOYED: Wed Mar 11 09:46:12 2020
NAMESPACE: default
STATUS: deployed
REVISION: 2
TEST SUITE: None

$ helm upgrade --install vault-operator banzaicloud-stable/vault-operator --namespace vault
Release "vault-operator" does not exist. Installing it now.
Error: rendered manifests contain a resource that already exists. Unable to continue with install: existing resource conflict: namespace: , name: vaults.vault.banzaicloud.com, existing_kind: apiextensions.k8s.io/v1beta1, Kind=CustomResourceDefinition, new_kind: apiextensions.k8s.io/v1beta1, Kind=CustomResourceDefinition
```

**Comment by akin-ozer** [comment]
Yes I did, wasn't aware that this was the problem. What can we do for fix? Is there any open issues about this in Helm?

**Comment by bonifaido** [comment]
I'm just searching in Helm issues right now, but I can't see any issue like this, probably it needs to be reported.

CRDs are cluster scoped objects, so this check in shouldn't be tied to the release namespace.

**Comment by akin-ozer** [comment]
One thing I didn't quite understand is, we should get this error if we have installed version already. But in my case there is no installed version(which you are reproduced with). How can I still get this error? I failed to mention that I am trying to get a fresh installation in each case. I can also fresh install with no problem using 0.6.4 after getting this.

**Comment by bonifaido** [comment]
If you remove the chart from every namespace and delete the vault CRD you should be able to install and upgrade it consistently to the same namespace.

**Comment by akin-ozer** [comment]
But it's already removed from everywhere. I can install 0.6.4 also, but for 0.6.7(again removing everything) still issue exists.

**Comment by bonifaido** [comment]
The chart was packaged with Helm2 and this caused the issue, another version will be released soon.
